### ISSUE TITLE
Peeping Tom

### ISSUE THREAD

**Issue by AgentJohnDoe** [RokasKil/EmoteLog#2]
Hey, I wonder if it's possible that you can update Peeping Tom as it seems to be abandoned by the creator Anna? Your plugin Emote Log goes hand in hand with it imo, and maybe it's even possible to merge them?

**Comment by RokasKil** [comment]
Hi, as far as I know she hasn't put it or any of the yet unupdated plugins up for adoption and it's only been two weeks since 7.1, devs have lives and priorities outside of ffxiv plugins, give her time.
